### PR TITLE
fixed bug with import_commits_as_strings.py

### PR DESCRIPTION
**Pull request by lylet-AC**
It now outputs a proper string

### CODE REVIEW

**Comment by ZachAndrews98** [comment]
Can you add some documentation for this function, ie what exactly should be sent to the function. I'm a little confused exactly what file_path is, does it point to a single file or does it point to the repository?

**Review by karolvargas — APPROVED** [review]

**Comment by lylet-AC** [comment]
A file path needs to be sent into the function to point it to the repo

**Review by burrowss — APPROVED** [review]

**Comment by ZachAndrews98** [comment]
So I have tried to run import_commits_as_string and followed the documentation to use pip to install dulwich. However, whenever I try to run gatorGauge with it I get "ImportError: No module named 'dulwich'". Is there some specific install command that I have to run and if so could you add that documentation to the readme.

**Comment by burrowss** [comment]
Before this gets merged, can you explain how to run your file so that it downloads the commits and makes them the string?

**Review by burrowss — COMMENTED** [review]
How does this actually get ran

**Review by burrowss — CHANGES_REQUESTED** [review]
How does this actually get ran

**Comment by lylet-AC** [comment]
I added this information to the requirements.txt in commit 5263659c44b028b5c3c083103549578f5a24d320 For some reason, this didn't get merged.

**Comment by lylet-AC** [comment]
To run this outside of installing the requirements, `pip install dulwich --global-option="--pure"`

**Comment by lylet-AC** [comment]
Here is an example of how to use it after installing python to get a string from a given file_path

>>> from import_commits_as_string import import_commits_as_string
>>> file_path = "../GatorGaugeSampleRepo"
>>> commit_str = import_commits_as_string(file_path)
>>> print(commit_str)

**Comment by lylet-AC** [comment]
@burrowss This also references issue #24

**Review by burrowss — APPROVED** [review]
I understand whats going on with this now. Will potentially be deleted later for better implementation

**Pull request merged**
