### PR TITLE
added commit counter

### PR DESCRIPTION
**Pull request by lylet-AC**
references issue #2

### CODE REVIEW

**Review by karolvargas — APPROVED** [review]

**Review by mariakimheinert — CHANGES_REQUESTED** [review]
@lylet-AC can't you get the value returned by `count_commits.py` by just taking the length of the list returned by `get_list_of_commits()`? I don't see the need for the `count_commits.py` function.

**Comment by lylet-AC** [comment]
@yeeunmariakim You can, however, I was directed to write this function. So I did.

**Comment by mariakimheinert** [comment]
@lylet-AC where are you using `count_commits.py`? If it's not being used yet, it would be best just to remove it.

**Comment by lylet-AC** [comment]
@yeeunmariakim ¯\_(ツ)_/¯ sounds fair to me

**Pull request closed without merging**
