### PR TITLE
documentation fixing

### PR DESCRIPTION
**Pull request by castellanosr**
Kapfhammer said our readMe was subpar so we're working on fixing that

### CODE REVIEW

**Comment by castellanosr** [comment]
Under "Project" there is a comment stating "name of the project to be pulled down". What does this mean? it needs to be changed/fixed.

**Comment by castellanosr** [comment]
There is an empty section titled "Commands" what was intended to be placed here? Something needs to be added or the section will be deleted.

**Comment by castellanosr** [comment]
Maybe the "Usage" section should be changed? It is currently just repeating what is already said. Something needs to be under "Usage," but I don't know what to change it to. Anyone have any ideas?

**Comment by castellanosr** [comment]
The "Functions Tested" section is currently empty. What functions have been tested that can be listed/explained in this section?

**Review by burrowss — APPROVED** [review]

**Review by bonnettd — APPROVED** [review]

**Pull request merged**
